### PR TITLE
Fixed a bug with the sequence number and with the motion parameters

### PR DESCRIPTION
**Pull request by bambam01**
The sequence number was never checked because of a bug in the if statement and it was never reset
The motion parameters where also never set because of the same bug in the if statement

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Just an fyi: the commit was not made with an email address recognised by GH. You may want to fix that before this PR gets merged.

**Comment by G-Paris** [comment]
Bambam has asked me to close this request so he can re-request with a recognized email address.

**Comment by gavanderhoorn** [comment]
For future reference: a local fixup of the commit followed by a force push to the same branch would also have worked.

**Comment by gavanderhoorn** [comment]
Ping? Is this PR going to be resubmitted?

**Pull request closed without merging**
